### ISSUE TITLE
Cannot save NIFMultiScale model

### ISSUE THREAD

**Issue by uribarri** [pswpswpsw/nif#4]
Attempting to save a NIFMultiScale model (or its subclasses) using model.save() or tf.saved_model.save() throws an error as below:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/dp/zr6n3k1d2lv5b2t917gfqlnm0000gn/T/ipykernel_83723/2345140346.py in <module>
----> 1 model.save('tut_2_model_multiscale')

~/miniconda3/envs/nif/lib/python3.10/site-packages/keras/utils/traceback_utils.py in error_handler(*args, **kwargs)
     68             # To get the full stack trace, call:
     69             # `tf.debugging.disable_traceback_filtering()`
---> 70             raise e.with_traceback(filtered_tb) from None
     71         finally:
     72             del filtered_tb

~/miniconda3/envs/nif/lib/python3.10/site-packages/google/protobuf/internal/python_message.py in field_setter(self, new_value)
    702       new_value = type_checker.CheckValue(new_value)
    703     except TypeError as e:
--> 704       raise TypeError(
    705           'Cannot set %s to %.1024r: %s' % (field.full_name, new_value, e))
    706     if clear_when_set_to_default and not new_value:

TypeError: Cannot set tensorflow.SavedVariable.trainable to 'float32': 'float32' has type <class 'str'>, but expected one of: (<class 'bool'>, <class 'numbers.Integral'>)
```

This originates in `HyperLinearForSIREN.__init__` where `self.w` and `self.b` are defined as `tf.Variable`s: `mixed_policy.variable_dtype` is given for a positional argument that belongs to `Variable`'s `training` argument. This issue is resolved by replacing these lines with `dtype=mixed_policy.variable_dtype`. I have a branch that implements this change that I can push if desired.

Although this fixes the problem with `tf.saved_model.save()`, using `model.save()` still throws other errors once this is resolved. It's unclear if these problems are with NIF or with a Tensorflow bug ([this issue](https://discuss.tensorflow.org/t/using-efficientnetb0-and-save-model-will-result-unable-to-serialize-2-0896919-2-1128857-2-1081853-to-json-unrecognized-type-class-tensorflow-python-framework-ops-eagertensor/12518)).

**Comment by yafshar** [comment]
@uribarri can you share your TF version, your OS, and if it is possible a small snippet of the code where this issue happens, or is it happening in general whenever you do `model.save()`?

**Comment by uribarri** [comment]
@yafshar I've had the issue on Mac OS 13.0 and Ubuntu 18.04, using TF 2.11.0 in both cases. It can be replicated by running the Tutorial 3 notebook and trying `model.save()` on the resulting model.

I have tried `model.save()` in a variety of other contexts as well. It works in Tutorial 1 and (I think) 2, where `HyperLinearForSIREN` is not used.

**Comment by pswpswpsw** [comment]
@uribarri Thanks for pointing out this issue. Actually I always use `model.save_weights` and `model.load_weights` to read or write a model. This is what we did in all of the tutorials. It works for `HyperLinearForSIREN `.

**Comment by aaron-philip** [comment]
Hello,

I am running into a similar issue with saving/loading. Although the methods save_weights/load_weights work fine, there is discrepancy between model predictions when a new model is created from a different NIFMultiScaleLastLayer constructor  (as is necessary when a user wants to use the trained model later). The same issue is not present in the NIFMultiScale constructors as I demonstrate below. I do not know if this is the same issue being run into by @uribarri. 

I am attaching a link to a modified version of your Colab Tutorial 3 that demonstrates the issue in detail. https://colab.research.google.com/drive/1W_5oaJS49wXjogjYqoDXH35aBgAFWEJx#scrollTo=N88gBLHrcVjL

Thank you!

**Comment by pswpswpsw** [comment]
@aaron-philip thanks for pointing out this error and preparing such a nice demo for illustration. This really helps me to figure out the issue. So the root cause is that I used `tf.Variable` to create trainable parameters for the last layer bias, which is not taken into account by the `Model` collects the trainable parameters. 

So I fixed this by writing a customized layer only doing the job of adding a bias. Now this bug is fixed. see here https://github.com/pswpswpsw/nif/blob/main/nif/model.py#L818

It seems like when using model subclassing, tensorflow can only collect trainable parameters when all forward pass is called through `Layer`.

**Comment by aaron-philip** [comment]
@pswpswpsw 

Hello, 
In model.py of nif: 
line 1138 : tf.cast(self.last_layer_bias, self.compute_Dtype)
should be commented out I believe in accordance with the last fix to allow the user to use model_x_to_u_given_w(). Please correct me If I am wrong, but it fixed my issue and seems to be the correct way to call _call_shape_net_mres_only_para_last_layer() now.
